version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app

  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Helloflask@1
    volumes:
      - hello-flask-mysql:/var/lib/mysql
      - hello-flask-mysql-config:/etc/mysql

volumes:
  hello-flask-mysql:
  hello-flask-mysql-config:
